name: Build Ghidra

on:
  push:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - platform: windows-11-arm
            java-distribution: microsoft

    runs-on: ${{ matrix.platform }}
    defaults:
      run:
        shell: bash
    steps:

      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Read Ghidra JDK Version
        run: echo "JDK_VER=$(awk -F'=' '$1=="application.java.min" {print $2}' Ghidra/application.properties)" >> $GITHUB_ENV

      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          distribution: '${{ matrix.java-distribution }}'
          java-version: '${{ env.JDK_VER }}'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
        with:
          gradle-version: nightly

      - name: Fetch Dependencies
        run: |
          mkdir -p "$RUNNER_TEMP/gradle-fetch"
          printf "rootProject.name='dependency-fetch'\n" > "$RUNNER_TEMP/gradle-fetch/settings.gradle"
          gradle -p "$RUNNER_TEMP/gradle-fetch" -I "$GITHUB_WORKSPACE/gradle/support/fetchDependencies.gradle" -DhideDownloadProgress -DnoEclipse help

      - name: Build Ghidra
        run: ./gradlew.bat buildGhidra --parallel

      - name: Upload distribution
        uses: actions/upload-artifact@v4
        with:
          name: ghidra-${{ matrix.platform }}
          path: build/dist/*.zip
          if-no-files-found: error
